[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "StatReformat"
description = "Reformats the stats displayed on upgrades consistently to: 'Damage: +30%'"
websiteUrl = "https://github.com/Little-Sparroh/StatReformat"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/StatReformat.dll"
target = "BepInEx/plugins/StatReformat.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


